# Same as Black.
line-length = 100
indent-width = 4

[lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default
select = ["D", "E", "F", "W", "I", "N", "UP", "ANN", "Q", "RUF", "ASYNC", "S", "B", "A", "C4", "T20", "SIM"]

ignore = [
  "ANN101", # Missing type annotation for {name} in method
  "ANN102", # Missing type annotation for {name} in classmethod
  "ANN202", # Missing return type annotation for private function {name}
  "ANN204", # Missing return type annotation for special method
  "ANN206", # Missing return type annotation for classmethod {name}
  "ANN401", # Dynamically typed expressions (typing.Any) are disallowed in {name}
  "D101",   # Missing docstring in public class
  "D104",   # Missing docstring in public package
  "D105",   # Missing docstring in magic method
  "D412",   # No blank lines allowed between a section header and its content ("{name}")
  "RUF010",
  "UP006",
  "UP007",
  "E501"
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.per-file-ignores]
"/**/test/*" = ["D", "ANN"]
"*test*" = ["S", "B"]

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
#
# This is currently disabled by default, but it is planned for this
# to be opt-out in the future.
docstring-code-format = true

# Set the line length limit used when formatting code snippets in
# docstrings.
#
# This only has an effect when the `docstring-code-format` setting is
# enabled.
docstring-code-line-length = "dynamic"

[lint.pydocstyle]
convention = "google"
